// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraper.proto

package scraper

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Get projects
type GetProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{0}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

type GetProjectsResponse struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsResponse) Reset()         { *m = GetProjectsResponse{} }
func (m *GetProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectsResponse) ProtoMessage()    {}
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{1}
}

func (m *GetProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsResponse.Unmarshal(m, b)
}
func (m *GetProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsResponse.Merge(m, src)
}
func (m *GetProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectsResponse.Size(m)
}
func (m *GetProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsResponse proto.InternalMessageInfo

func (m *GetProjectsResponse) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GetProjectsResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Get Spiders
type GetSpidersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidersRequest) Reset()         { *m = GetSpidersRequest{} }
func (m *GetSpidersRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpidersRequest) ProtoMessage()    {}
func (*GetSpidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{2}
}

func (m *GetSpidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidersRequest.Unmarshal(m, b)
}
func (m *GetSpidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidersRequest.Marshal(b, m, deterministic)
}
func (m *GetSpidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidersRequest.Merge(m, src)
}
func (m *GetSpidersRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpidersRequest.Size(m)
}
func (m *GetSpidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidersRequest proto.InternalMessageInfo

type GetSpidersResponse struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidersResponse) Reset()         { *m = GetSpidersResponse{} }
func (m *GetSpidersResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpidersResponse) ProtoMessage()    {}
func (*GetSpidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{3}
}

func (m *GetSpidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidersResponse.Unmarshal(m, b)
}
func (m *GetSpidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidersResponse.Marshal(b, m, deterministic)
}
func (m *GetSpidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidersResponse.Merge(m, src)
}
func (m *GetSpidersResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpidersResponse.Size(m)
}
func (m *GetSpidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidersResponse proto.InternalMessageInfo

func (m *GetSpidersResponse) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GetSpidersResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Scheduler spider
type ScheduleSpiderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleSpiderRequest) Reset()         { *m = ScheduleSpiderRequest{} }
func (m *ScheduleSpiderRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleSpiderRequest) ProtoMessage()    {}
func (*ScheduleSpiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{4}
}

func (m *ScheduleSpiderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleSpiderRequest.Unmarshal(m, b)
}
func (m *ScheduleSpiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleSpiderRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleSpiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleSpiderRequest.Merge(m, src)
}
func (m *ScheduleSpiderRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleSpiderRequest.Size(m)
}
func (m *ScheduleSpiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleSpiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleSpiderRequest proto.InternalMessageInfo

func (m *ScheduleSpiderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScheduleSpiderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type ScheduleSpiderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleSpiderResponse) Reset()         { *m = ScheduleSpiderResponse{} }
func (m *ScheduleSpiderResponse) String() string { return proto.CompactTextString(m) }
func (*ScheduleSpiderResponse) ProtoMessage()    {}
func (*ScheduleSpiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{5}
}

func (m *ScheduleSpiderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleSpiderResponse.Unmarshal(m, b)
}
func (m *ScheduleSpiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleSpiderResponse.Marshal(b, m, deterministic)
}
func (m *ScheduleSpiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleSpiderResponse.Merge(m, src)
}
func (m *ScheduleSpiderResponse) XXX_Size() int {
	return xxx_messageInfo_ScheduleSpiderResponse.Size(m)
}
func (m *ScheduleSpiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleSpiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleSpiderResponse proto.InternalMessageInfo

func (m *ScheduleSpiderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Cancel spider
type CancelScheduleSpiderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelScheduleSpiderRequest) Reset()         { *m = CancelScheduleSpiderRequest{} }
func (m *CancelScheduleSpiderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelScheduleSpiderRequest) ProtoMessage()    {}
func (*CancelScheduleSpiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{6}
}

func (m *CancelScheduleSpiderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelScheduleSpiderRequest.Unmarshal(m, b)
}
func (m *CancelScheduleSpiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelScheduleSpiderRequest.Marshal(b, m, deterministic)
}
func (m *CancelScheduleSpiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelScheduleSpiderRequest.Merge(m, src)
}
func (m *CancelScheduleSpiderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelScheduleSpiderRequest.Size(m)
}
func (m *CancelScheduleSpiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelScheduleSpiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelScheduleSpiderRequest proto.InternalMessageInfo

func (m *CancelScheduleSpiderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CancelScheduleSpiderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type CancelScheduleSpiderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelScheduleSpiderResponse) Reset()         { *m = CancelScheduleSpiderResponse{} }
func (m *CancelScheduleSpiderResponse) String() string { return proto.CompactTextString(m) }
func (*CancelScheduleSpiderResponse) ProtoMessage()    {}
func (*CancelScheduleSpiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{7}
}

func (m *CancelScheduleSpiderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelScheduleSpiderResponse.Unmarshal(m, b)
}
func (m *CancelScheduleSpiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelScheduleSpiderResponse.Marshal(b, m, deterministic)
}
func (m *CancelScheduleSpiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelScheduleSpiderResponse.Merge(m, src)
}
func (m *CancelScheduleSpiderResponse) XXX_Size() int {
	return xxx_messageInfo_CancelScheduleSpiderResponse.Size(m)
}
func (m *CancelScheduleSpiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelScheduleSpiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelScheduleSpiderResponse proto.InternalMessageInfo

func (m *CancelScheduleSpiderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Run Spiders
type RunSpiderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSpiderRequest) Reset()         { *m = RunSpiderRequest{} }
func (m *RunSpiderRequest) String() string { return proto.CompactTextString(m) }
func (*RunSpiderRequest) ProtoMessage()    {}
func (*RunSpiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{8}
}

func (m *RunSpiderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSpiderRequest.Unmarshal(m, b)
}
func (m *RunSpiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSpiderRequest.Marshal(b, m, deterministic)
}
func (m *RunSpiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSpiderRequest.Merge(m, src)
}
func (m *RunSpiderRequest) XXX_Size() int {
	return xxx_messageInfo_RunSpiderRequest.Size(m)
}
func (m *RunSpiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSpiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunSpiderRequest proto.InternalMessageInfo

func (m *RunSpiderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RunSpiderResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSpiderResponse) Reset()         { *m = RunSpiderResponse{} }
func (m *RunSpiderResponse) String() string { return proto.CompactTextString(m) }
func (*RunSpiderResponse) ProtoMessage()    {}
func (*RunSpiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{9}
}

func (m *RunSpiderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSpiderResponse.Unmarshal(m, b)
}
func (m *RunSpiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSpiderResponse.Marshal(b, m, deterministic)
}
func (m *RunSpiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSpiderResponse.Merge(m, src)
}
func (m *RunSpiderResponse) XXX_Size() int {
	return xxx_messageInfo_RunSpiderResponse.Size(m)
}
func (m *RunSpiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSpiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunSpiderResponse proto.InternalMessageInfo

func (m *RunSpiderResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Get jobs
type Job struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SpiderName           string   `protobuf:"bytes,2,opt,name=spiderName,proto3" json:"spiderName,omitempty"`
	StartDate            string   `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{10}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetSpiderName() string {
	if m != nil {
		return m.SpiderName
	}
	return ""
}

func (m *Job) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Job) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type GetJobsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsRequest) Reset()         { *m = GetJobsRequest{} }
func (m *GetJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobsRequest) ProtoMessage()    {}
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{11}
}

func (m *GetJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsRequest.Unmarshal(m, b)
}
func (m *GetJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsRequest.Merge(m, src)
}
func (m *GetJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobsRequest.Size(m)
}
func (m *GetJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsRequest proto.InternalMessageInfo

func (m *GetJobsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type GetJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsResponse) Reset()         { *m = GetJobsResponse{} }
func (m *GetJobsResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobsResponse) ProtoMessage()    {}
func (*GetJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{12}
}

func (m *GetJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsResponse.Unmarshal(m, b)
}
func (m *GetJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsResponse.Marshal(b, m, deterministic)
}
func (m *GetJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsResponse.Merge(m, src)
}
func (m *GetJobsResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobsResponse.Size(m)
}
func (m *GetJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsResponse proto.InternalMessageInfo

func (m *GetJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *GetJobsResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Get job
type GetJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{13}
}

func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (m *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(m, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetJobResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobResponse) Reset()         { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()    {}
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{14}
}

func (m *GetJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobResponse.Unmarshal(m, b)
}
func (m *GetJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobResponse.Marshal(b, m, deterministic)
}
func (m *GetJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobResponse.Merge(m, src)
}
func (m *GetJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobResponse.Size(m)
}
func (m *GetJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobResponse proto.InternalMessageInfo

func (m *GetJobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Cancel job
type CancelJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobRequest) Reset()         { *m = CancelJobRequest{} }
func (m *CancelJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelJobRequest) ProtoMessage()    {}
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{15}
}

func (m *CancelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobRequest.Unmarshal(m, b)
}
func (m *CancelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobRequest.Merge(m, src)
}
func (m *CancelJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelJobRequest.Size(m)
}
func (m *CancelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobRequest proto.InternalMessageInfo

func (m *CancelJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CancelJobResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobResponse) Reset()         { *m = CancelJobResponse{} }
func (m *CancelJobResponse) String() string { return proto.CompactTextString(m) }
func (*CancelJobResponse) ProtoMessage()    {}
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{16}
}

func (m *CancelJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobResponse.Unmarshal(m, b)
}
func (m *CancelJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobResponse.Marshal(b, m, deterministic)
}
func (m *CancelJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobResponse.Merge(m, src)
}
func (m *CancelJobResponse) XXX_Size() int {
	return xxx_messageInfo_CancelJobResponse.Size(m)
}
func (m *CancelJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobResponse proto.InternalMessageInfo

func (m *CancelJobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProjectsRequest)(nil), "scraper.getProjectsRequest")
	proto.RegisterType((*GetProjectsResponse)(nil), "scraper.getProjectsResponse")
	proto.RegisterType((*GetSpidersRequest)(nil), "scraper.getSpidersRequest")
	proto.RegisterType((*GetSpidersResponse)(nil), "scraper.getSpidersResponse")
	proto.RegisterType((*ScheduleSpiderRequest)(nil), "scraper.scheduleSpiderRequest")
	proto.RegisterType((*ScheduleSpiderResponse)(nil), "scraper.scheduleSpiderResponse")
	proto.RegisterType((*CancelScheduleSpiderRequest)(nil), "scraper.cancelScheduleSpiderRequest")
	proto.RegisterType((*CancelScheduleSpiderResponse)(nil), "scraper.cancelScheduleSpiderResponse")
	proto.RegisterType((*RunSpiderRequest)(nil), "scraper.runSpiderRequest")
	proto.RegisterType((*RunSpiderResponse)(nil), "scraper.runSpiderResponse")
	proto.RegisterType((*Job)(nil), "scraper.Job")
	proto.RegisterType((*GetJobsRequest)(nil), "scraper.getJobsRequest")
	proto.RegisterType((*GetJobsResponse)(nil), "scraper.getJobsResponse")
	proto.RegisterType((*GetJobRequest)(nil), "scraper.getJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "scraper.getJobResponse")
	proto.RegisterType((*CancelJobRequest)(nil), "scraper.cancelJobRequest")
	proto.RegisterType((*CancelJobResponse)(nil), "scraper.cancelJobResponse")
}

func init() {
	proto.RegisterFile("scraper.proto", fileDescriptor_afbcebd6a39f4560)
}

var fileDescriptor_afbcebd6a39f4560 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x5b, 0x6f, 0xda, 0x3c,
	0x1c, 0xc6, 0x0b, 0x44, 0xf0, 0xe6, 0xe9, 0x0b, 0x2b, 0xee, 0x4a, 0xb3, 0x80, 0x5a, 0x64, 0x6d,
	0x13, 0x5a, 0xa5, 0x6a, 0xea, 0xa4, 0xdd, 0x4c, 0xda, 0xa9, 0xad, 0x90, 0x98, 0x34, 0x4d, 0xe1,
	0x6e, 0x77, 0x39, 0x78, 0x2c, 0x55, 0x9b, 0x64, 0xb1, 0xb3, 0x2f, 0xbd, 0x2f, 0x31, 0xcd, 0x89,
	0x8d, 0x81, 0x00, 0xd2, 0x76, 0x17, 0xff, 0x0f, 0xbf, 0xc7, 0x87, 0xe7, 0x0f, 0xe8, 0xf2, 0x30,
	0xf7, 0x33, 0x96, 0x5f, 0x66, 0x79, 0x2a, 0x52, 0xd2, 0xa9, 0x96, 0xf4, 0x31, 0xc8, 0x82, 0x89,
	0x2f, 0x79, 0x7a, 0xc7, 0x42, 0xc1, 0x3d, 0xf6, 0xa3, 0x60, 0x5c, 0xd0, 0x0f, 0x38, 0x5e, 0x89,
	0xf2, 0x2c, 0x4d, 0x38, 0x23, 0x04, 0x56, 0xe2, 0x3f, 0x30, 0xa7, 0x31, 0x6e, 0x4d, 0x6c, 0x4f,
	0x7e, 0x93, 0x01, 0xda, 0x5c, 0xf8, 0xa2, 0xe0, 0x4e, 0x73, 0xdc, 0x98, 0xfc, 0xe7, 0x55, 0x2b,
	0x7a, 0x8c, 0xfe, 0x82, 0x89, 0x79, 0x16, 0x47, 0x2c, 0xd7, 0xdc, 0xf7, 0x52, 0x4d, 0x07, 0xff,
	0x02, 0xfb, 0x0e, 0x27, 0x3c, 0xfc, 0xce, 0xa2, 0xe2, 0x9e, 0x95, 0x98, 0x0a, 0x6d, 0x40, 0x1a,
	0x1a, 0x42, 0x60, 0x89, 0xf8, 0x81, 0x49, 0x84, 0xed, 0xc9, 0x6f, 0xfa, 0x12, 0x83, 0x75, 0x40,
	0xb5, 0x8d, 0xa5, 0x64, 0xc9, 0x50, 0x92, 0xb7, 0x18, 0x86, 0x7e, 0x12, 0xb2, 0xfb, 0xf9, 0x3f,
	0x09, 0xbf, 0xc6, 0xa8, 0x1e, 0xb3, 0x47, 0xfe, 0x39, 0x8e, 0xf2, 0x22, 0xd9, 0xab, 0x49, 0x2f,
	0xd0, 0x37, 0xea, 0x6a, 0xa1, 0xcb, 0x6b, 0x2c, 0xd0, 0x9a, 0xa5, 0xc1, 0x36, 0x4d, 0x72, 0x06,
	0x70, 0x09, 0xfa, 0xec, 0xeb, 0x53, 0x18, 0x11, 0x32, 0x82, 0xcd, 0x85, 0x9f, 0x8b, 0x1b, 0x5f,
	0x30, 0xa7, 0x25, 0xd3, 0xcb, 0x00, 0x71, 0xd0, 0x61, 0x49, 0x24, 0x73, 0x96, 0xcc, 0xa9, 0x25,
	0x7d, 0x81, 0xde, 0x82, 0x89, 0x59, 0x1a, 0x28, 0x47, 0xfc, 0xa9, 0xcd, 0x4a, 0x9b, 0x55, 0x5b,
	0x50, 0x4b, 0xfa, 0x09, 0x8f, 0x74, 0x6d, 0x75, 0x9a, 0x31, 0xac, 0xbb, 0x34, 0xe0, 0xd2, 0x28,
	0x87, 0x57, 0xff, 0x5f, 0x2a, 0x4f, 0xcf, 0xd2, 0xc0, 0x93, 0x99, 0xad, 0xb6, 0x39, 0x47, 0xb7,
	0x84, 0x29, 0xdd, 0x1e, 0x9a, 0x71, 0x54, 0x49, 0x36, 0xe3, 0x88, 0x4e, 0xd4, 0xce, 0xf6, 0xbe,
	0x07, 0xc5, 0x51, 0xf9, 0x8e, 0x3b, 0x68, 0x17, 0xe8, 0x1b, 0x35, 0xbb, 0x81, 0x57, 0xbf, 0x2c,
	0x74, 0xcb, 0x67, 0x9b, 0xb3, 0xfc, 0x67, 0x1c, 0x32, 0x32, 0xc3, 0xe1, 0x74, 0x39, 0x7e, 0x64,
	0xa8, 0x0f, 0xba, 0x39, 0xaa, 0xee, 0xa8, 0x3e, 0x59, 0x6a, 0xd2, 0x03, 0x32, 0x05, 0xa6, 0x7a,
	0xe4, 0x88, 0x6b, 0x56, 0xaf, 0x0e, 0xa7, 0x3b, 0xac, 0xcd, 0x69, 0xd0, 0x2d, 0xe0, 0x29, 0x7f,
	0x71, 0xf2, 0x44, 0x17, 0xaf, 0x9b, 0xd3, 0x75, 0xeb, 0x52, 0x1a, 0x33, 0x47, 0x6f, 0x75, 0x00,
	0xc8, 0x99, 0xae, 0xaf, 0x9d, 0x6c, 0xf7, 0x7c, 0x6b, 0x5e, 0x43, 0xbf, 0xe1, 0xe4, 0xba, 0x66,
	0xb6, 0x38, 0x79, 0xaa, 0x7b, 0x77, 0x8c, 0xb0, 0xfb, 0x6c, 0x4f, 0x95, 0xd6, 0x79, 0x8b, 0xce,
	0xb4, 0xf4, 0x24, 0x39, 0x35, 0x6f, 0xcb, 0x70, 0xb4, 0xeb, 0x6c, 0x26, 0x74, 0xff, 0x1b, 0xb4,
	0xcb, 0x7e, 0x32, 0x58, 0xab, 0x52, 0xdd, 0xa7, 0x1b, 0x71, 0xdd, 0x7c, 0x03, 0xfb, 0x5a, 0x99,
	0xca, 0xb8, 0xff, 0x75, 0x33, 0x1a, 0xf7, 0xbf, 0xe1, 0x41, 0x7a, 0xf0, 0xd1, 0xfe, 0xaa, 0x7e,
	0xfb, 0x83, 0xb6, 0xfc, 0x2f, 0x78, 0xf5, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xa5, 0x8c, 0x6e,
	0x1c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpiderServiceClient is the client API for SpiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpiderServiceClient interface {
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	GetSpiders(ctx context.Context, in *GetSpidersRequest, opts ...grpc.CallOption) (*GetSpidersResponse, error)
	RunSpiders(ctx context.Context, in *RunSpiderRequest, opts ...grpc.CallOption) (*RunSpiderResponse, error)
	ScheduleSpider(ctx context.Context, in *ScheduleSpiderRequest, opts ...grpc.CallOption) (*ScheduleSpiderResponse, error)
	CancelScheduleSpiders(ctx context.Context, in *CancelScheduleSpiderRequest, opts ...grpc.CallOption) (*CancelScheduleSpiderResponse, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
}

type spiderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderServiceClient(cc grpc.ClientConnInterface) SpiderServiceClient {
	return &spiderServiceClient{cc}
}

func (c *spiderServiceClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) GetSpiders(ctx context.Context, in *GetSpidersRequest, opts ...grpc.CallOption) (*GetSpidersResponse, error) {
	out := new(GetSpidersResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/GetSpiders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) RunSpiders(ctx context.Context, in *RunSpiderRequest, opts ...grpc.CallOption) (*RunSpiderResponse, error) {
	out := new(RunSpiderResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/RunSpiders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) ScheduleSpider(ctx context.Context, in *ScheduleSpiderRequest, opts ...grpc.CallOption) (*ScheduleSpiderResponse, error) {
	out := new(ScheduleSpiderResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/ScheduleSpider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) CancelScheduleSpiders(ctx context.Context, in *CancelScheduleSpiderRequest, opts ...grpc.CallOption) (*CancelScheduleSpiderResponse, error) {
	out := new(CancelScheduleSpiderResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/CancelScheduleSpiders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error) {
	out := new(GetJobsResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/GetJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, "/scraper.SpiderService/CancelJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServiceServer is the server API for SpiderService service.
type SpiderServiceServer interface {
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	GetSpiders(context.Context, *GetSpidersRequest) (*GetSpidersResponse, error)
	RunSpiders(context.Context, *RunSpiderRequest) (*RunSpiderResponse, error)
	ScheduleSpider(context.Context, *ScheduleSpiderRequest) (*ScheduleSpiderResponse, error)
	CancelScheduleSpiders(context.Context, *CancelScheduleSpiderRequest) (*CancelScheduleSpiderResponse, error)
	GetJobs(context.Context, *GetJobsRequest) (*GetJobsResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
}

// UnimplementedSpiderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSpiderServiceServer struct {
}

func (*UnimplementedSpiderServiceServer) GetProjects(ctx context.Context, req *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (*UnimplementedSpiderServiceServer) GetSpiders(ctx context.Context, req *GetSpidersRequest) (*GetSpidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpiders not implemented")
}
func (*UnimplementedSpiderServiceServer) RunSpiders(ctx context.Context, req *RunSpiderRequest) (*RunSpiderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSpiders not implemented")
}
func (*UnimplementedSpiderServiceServer) ScheduleSpider(ctx context.Context, req *ScheduleSpiderRequest) (*ScheduleSpiderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleSpider not implemented")
}
func (*UnimplementedSpiderServiceServer) CancelScheduleSpiders(ctx context.Context, req *CancelScheduleSpiderRequest) (*CancelScheduleSpiderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelScheduleSpiders not implemented")
}
func (*UnimplementedSpiderServiceServer) GetJobs(ctx context.Context, req *GetJobsRequest) (*GetJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (*UnimplementedSpiderServiceServer) GetJob(ctx context.Context, req *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (*UnimplementedSpiderServiceServer) CancelJob(ctx context.Context, req *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}

func RegisterSpiderServiceServer(s *grpc.Server, srv SpiderServiceServer) {
	s.RegisterService(&_SpiderService_serviceDesc, srv)
}

func _SpiderService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_GetSpiders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).GetSpiders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/GetSpiders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).GetSpiders(ctx, req.(*GetSpidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_RunSpiders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSpiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).RunSpiders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/RunSpiders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).RunSpiders(ctx, req.(*RunSpiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_ScheduleSpider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleSpiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).ScheduleSpider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/ScheduleSpider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).ScheduleSpider(ctx, req.(*ScheduleSpiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_CancelScheduleSpiders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelScheduleSpiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).CancelScheduleSpiders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/CancelScheduleSpiders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).CancelScheduleSpiders(ctx, req.(*CancelScheduleSpiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/GetJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiderService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraper.SpiderService/CancelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpiderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.SpiderService",
	HandlerType: (*SpiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _SpiderService_GetProjects_Handler,
		},
		{
			MethodName: "GetSpiders",
			Handler:    _SpiderService_GetSpiders_Handler,
		},
		{
			MethodName: "RunSpiders",
			Handler:    _SpiderService_RunSpiders_Handler,
		},
		{
			MethodName: "ScheduleSpider",
			Handler:    _SpiderService_ScheduleSpider_Handler,
		},
		{
			MethodName: "CancelScheduleSpiders",
			Handler:    _SpiderService_CancelScheduleSpiders_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _SpiderService_GetJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _SpiderService_GetJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _SpiderService_CancelJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraper.proto",
}
