// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraper.proto

package spider

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Get projects
type GetProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{0}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

type GetProjectsResponse struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsResponse) Reset()         { *m = GetProjectsResponse{} }
func (m *GetProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectsResponse) ProtoMessage()    {}
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{1}
}

func (m *GetProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsResponse.Unmarshal(m, b)
}
func (m *GetProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsResponse.Merge(m, src)
}
func (m *GetProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectsResponse.Size(m)
}
func (m *GetProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsResponse proto.InternalMessageInfo

func (m *GetProjectsResponse) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GetProjectsResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Get Spiders
type GetSpidersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidersRequest) Reset()         { *m = GetSpidersRequest{} }
func (m *GetSpidersRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpidersRequest) ProtoMessage()    {}
func (*GetSpidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{2}
}

func (m *GetSpidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidersRequest.Unmarshal(m, b)
}
func (m *GetSpidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidersRequest.Marshal(b, m, deterministic)
}
func (m *GetSpidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidersRequest.Merge(m, src)
}
func (m *GetSpidersRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpidersRequest.Size(m)
}
func (m *GetSpidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidersRequest proto.InternalMessageInfo

type GetSpidersResponse struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidersResponse) Reset()         { *m = GetSpidersResponse{} }
func (m *GetSpidersResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpidersResponse) ProtoMessage()    {}
func (*GetSpidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{3}
}

func (m *GetSpidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidersResponse.Unmarshal(m, b)
}
func (m *GetSpidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidersResponse.Marshal(b, m, deterministic)
}
func (m *GetSpidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidersResponse.Merge(m, src)
}
func (m *GetSpidersResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpidersResponse.Size(m)
}
func (m *GetSpidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidersResponse proto.InternalMessageInfo

func (m *GetSpidersResponse) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GetSpidersResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Scheduler spider
type ScheduleSpiderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleSpiderRequest) Reset()         { *m = ScheduleSpiderRequest{} }
func (m *ScheduleSpiderRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleSpiderRequest) ProtoMessage()    {}
func (*ScheduleSpiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{4}
}

func (m *ScheduleSpiderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleSpiderRequest.Unmarshal(m, b)
}
func (m *ScheduleSpiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleSpiderRequest.Marshal(b, m, deterministic)
}
func (m *ScheduleSpiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleSpiderRequest.Merge(m, src)
}
func (m *ScheduleSpiderRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleSpiderRequest.Size(m)
}
func (m *ScheduleSpiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleSpiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleSpiderRequest proto.InternalMessageInfo

func (m *ScheduleSpiderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScheduleSpiderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type ScheduleSpiderResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleSpiderResponse) Reset()         { *m = ScheduleSpiderResponse{} }
func (m *ScheduleSpiderResponse) String() string { return proto.CompactTextString(m) }
func (*ScheduleSpiderResponse) ProtoMessage()    {}
func (*ScheduleSpiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{5}
}

func (m *ScheduleSpiderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleSpiderResponse.Unmarshal(m, b)
}
func (m *ScheduleSpiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleSpiderResponse.Marshal(b, m, deterministic)
}
func (m *ScheduleSpiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleSpiderResponse.Merge(m, src)
}
func (m *ScheduleSpiderResponse) XXX_Size() int {
	return xxx_messageInfo_ScheduleSpiderResponse.Size(m)
}
func (m *ScheduleSpiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleSpiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleSpiderResponse proto.InternalMessageInfo

func (m *ScheduleSpiderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Cancel spider
type CancelScheduleSpiderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelScheduleSpiderRequest) Reset()         { *m = CancelScheduleSpiderRequest{} }
func (m *CancelScheduleSpiderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelScheduleSpiderRequest) ProtoMessage()    {}
func (*CancelScheduleSpiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{6}
}

func (m *CancelScheduleSpiderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelScheduleSpiderRequest.Unmarshal(m, b)
}
func (m *CancelScheduleSpiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelScheduleSpiderRequest.Marshal(b, m, deterministic)
}
func (m *CancelScheduleSpiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelScheduleSpiderRequest.Merge(m, src)
}
func (m *CancelScheduleSpiderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelScheduleSpiderRequest.Size(m)
}
func (m *CancelScheduleSpiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelScheduleSpiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelScheduleSpiderRequest proto.InternalMessageInfo

func (m *CancelScheduleSpiderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CancelScheduleSpiderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type CancelScheduleResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelScheduleResponse) Reset()         { *m = CancelScheduleResponse{} }
func (m *CancelScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*CancelScheduleResponse) ProtoMessage()    {}
func (*CancelScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{7}
}

func (m *CancelScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelScheduleResponse.Unmarshal(m, b)
}
func (m *CancelScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelScheduleResponse.Marshal(b, m, deterministic)
}
func (m *CancelScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelScheduleResponse.Merge(m, src)
}
func (m *CancelScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_CancelScheduleResponse.Size(m)
}
func (m *CancelScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelScheduleResponse proto.InternalMessageInfo

func (m *CancelScheduleResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Run Spiders
type RunSpiderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSpiderRequest) Reset()         { *m = RunSpiderRequest{} }
func (m *RunSpiderRequest) String() string { return proto.CompactTextString(m) }
func (*RunSpiderRequest) ProtoMessage()    {}
func (*RunSpiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{8}
}

func (m *RunSpiderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSpiderRequest.Unmarshal(m, b)
}
func (m *RunSpiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSpiderRequest.Marshal(b, m, deterministic)
}
func (m *RunSpiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSpiderRequest.Merge(m, src)
}
func (m *RunSpiderRequest) XXX_Size() int {
	return xxx_messageInfo_RunSpiderRequest.Size(m)
}
func (m *RunSpiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSpiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunSpiderRequest proto.InternalMessageInfo

func (m *RunSpiderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RunSpiderResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSpiderResponse) Reset()         { *m = RunSpiderResponse{} }
func (m *RunSpiderResponse) String() string { return proto.CompactTextString(m) }
func (*RunSpiderResponse) ProtoMessage()    {}
func (*RunSpiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{9}
}

func (m *RunSpiderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSpiderResponse.Unmarshal(m, b)
}
func (m *RunSpiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSpiderResponse.Marshal(b, m, deterministic)
}
func (m *RunSpiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSpiderResponse.Merge(m, src)
}
func (m *RunSpiderResponse) XXX_Size() int {
	return xxx_messageInfo_RunSpiderResponse.Size(m)
}
func (m *RunSpiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSpiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunSpiderResponse proto.InternalMessageInfo

func (m *RunSpiderResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Get jobs
type Job struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SpiderName           string   `protobuf:"bytes,2,opt,name=spiderName,proto3" json:"spiderName,omitempty"`
	StartDate            string   `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{10}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetSpiderName() string {
	if m != nil {
		return m.SpiderName
	}
	return ""
}

func (m *Job) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Job) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type GetJobsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsRequest) Reset()         { *m = GetJobsRequest{} }
func (m *GetJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobsRequest) ProtoMessage()    {}
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{11}
}

func (m *GetJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsRequest.Unmarshal(m, b)
}
func (m *GetJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsRequest.Merge(m, src)
}
func (m *GetJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobsRequest.Size(m)
}
func (m *GetJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsRequest proto.InternalMessageInfo

func (m *GetJobsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type GetJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsResponse) Reset()         { *m = GetJobsResponse{} }
func (m *GetJobsResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobsResponse) ProtoMessage()    {}
func (*GetJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{12}
}

func (m *GetJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsResponse.Unmarshal(m, b)
}
func (m *GetJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsResponse.Marshal(b, m, deterministic)
}
func (m *GetJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsResponse.Merge(m, src)
}
func (m *GetJobsResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobsResponse.Size(m)
}
func (m *GetJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsResponse proto.InternalMessageInfo

func (m *GetJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *GetJobsResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//Get job
type GetJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{13}
}

func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (m *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(m, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetJobJobResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobJobResponse) Reset()         { *m = GetJobJobResponse{} }
func (m *GetJobJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobJobResponse) ProtoMessage()    {}
func (*GetJobJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{14}
}

func (m *GetJobJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobJobResponse.Unmarshal(m, b)
}
func (m *GetJobJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobJobResponse.Marshal(b, m, deterministic)
}
func (m *GetJobJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobJobResponse.Merge(m, src)
}
func (m *GetJobJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobJobResponse.Size(m)
}
func (m *GetJobJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobJobResponse proto.InternalMessageInfo

func (m *GetJobJobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

//Cancel job
type CancelJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobRequest) Reset()         { *m = CancelJobRequest{} }
func (m *CancelJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelJobRequest) ProtoMessage()    {}
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{15}
}

func (m *CancelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobRequest.Unmarshal(m, b)
}
func (m *CancelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobRequest.Merge(m, src)
}
func (m *CancelJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelJobRequest.Size(m)
}
func (m *CancelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobRequest proto.InternalMessageInfo

func (m *CancelJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CancelJobResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobResponse) Reset()         { *m = CancelJobResponse{} }
func (m *CancelJobResponse) String() string { return proto.CompactTextString(m) }
func (*CancelJobResponse) ProtoMessage()    {}
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afbcebd6a39f4560, []int{16}
}

func (m *CancelJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobResponse.Unmarshal(m, b)
}
func (m *CancelJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobResponse.Marshal(b, m, deterministic)
}
func (m *CancelJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobResponse.Merge(m, src)
}
func (m *CancelJobResponse) XXX_Size() int {
	return xxx_messageInfo_CancelJobResponse.Size(m)
}
func (m *CancelJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobResponse proto.InternalMessageInfo

func (m *CancelJobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProjectsRequest)(nil), "spider.getProjectsRequest")
	proto.RegisterType((*GetProjectsResponse)(nil), "spider.getProjectsResponse")
	proto.RegisterType((*GetSpidersRequest)(nil), "spider.getSpidersRequest")
	proto.RegisterType((*GetSpidersResponse)(nil), "spider.getSpidersResponse")
	proto.RegisterType((*ScheduleSpiderRequest)(nil), "spider.scheduleSpiderRequest")
	proto.RegisterType((*ScheduleSpiderResponse)(nil), "spider.scheduleSpiderResponse")
	proto.RegisterType((*CancelScheduleSpiderRequest)(nil), "spider.cancelScheduleSpiderRequest")
	proto.RegisterType((*CancelScheduleResponse)(nil), "spider.cancelScheduleResponse")
	proto.RegisterType((*RunSpiderRequest)(nil), "spider.runSpiderRequest")
	proto.RegisterType((*RunSpiderResponse)(nil), "spider.runSpiderResponse")
	proto.RegisterType((*Job)(nil), "spider.Job")
	proto.RegisterType((*GetJobsRequest)(nil), "spider.getJobsRequest")
	proto.RegisterType((*GetJobsResponse)(nil), "spider.getJobsResponse")
	proto.RegisterType((*GetJobRequest)(nil), "spider.getJobRequest")
	proto.RegisterType((*GetJobJobResponse)(nil), "spider.getJobJobResponse")
	proto.RegisterType((*CancelJobRequest)(nil), "spider.cancelJobRequest")
	proto.RegisterType((*CancelJobResponse)(nil), "spider.cancelJobResponse")
}

func init() {
	proto.RegisterFile("scraper.proto", fileDescriptor_afbcebd6a39f4560)
}

var fileDescriptor_afbcebd6a39f4560 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x4f, 0xc2, 0x30,
	0x10, 0xc7, 0x03, 0x2c, 0x08, 0x47, 0xf8, 0x55, 0x94, 0x2c, 0xd1, 0x08, 0xe9, 0x83, 0x21, 0x9a,
	0x10, 0x83, 0x7f, 0x80, 0x3f, 0xa2, 0x2f, 0x7b, 0x30, 0x66, 0xbc, 0xf9, 0xd6, 0x6d, 0x17, 0x1c,
	0x81, 0x75, 0xb6, 0x9d, 0x7f, 0xbf, 0xa1, 0xed, 0xc6, 0x30, 0x02, 0x89, 0xbe, 0xf5, 0xee, 0xbe,
	0xf9, 0x7c, 0xaf, 0xbd, 0x2b, 0xb4, 0x65, 0x28, 0x58, 0x8a, 0x62, 0x9a, 0x0a, 0xae, 0x38, 0xa9,
	0xcb, 0x34, 0x8e, 0x50, 0xd0, 0x53, 0x20, 0x0b, 0x54, 0x6f, 0x82, 0x2f, 0x31, 0x54, 0xd2, 0xc7,
	0xcf, 0x0c, 0xa5, 0xa2, 0x8f, 0x30, 0xd8, 0xc9, 0xca, 0x94, 0x27, 0x12, 0x09, 0x01, 0x27, 0x61,
	0x6b, 0x74, 0x2b, 0xe3, 0xda, 0xa4, 0xe9, 0xeb, 0x33, 0x19, 0x42, 0x5d, 0x2a, 0xa6, 0x32, 0xe9,
	0x56, 0xc7, 0x95, 0x49, 0xc3, 0xb7, 0x11, 0x1d, 0x40, 0x7f, 0x81, 0x6a, 0xae, 0x5d, 0x0a, 0xee,
	0x83, 0x76, 0x2b, 0x92, 0x7f, 0xc0, 0xde, 0xc3, 0x99, 0x0c, 0x3f, 0x30, 0xca, 0x56, 0x68, 0x30,
	0x16, 0x5d, 0x82, 0x54, 0x0a, 0x08, 0x01, 0x47, 0xc5, 0x6b, 0xd4, 0x88, 0xa6, 0xaf, 0xcf, 0xf4,
	0x16, 0x86, 0x3f, 0x01, 0xb6, 0x8d, 0xad, 0xa5, 0x61, 0xe4, 0x96, 0x2f, 0x70, 0x1e, 0xb2, 0x24,
	0xc4, 0xd5, 0xfc, 0xbf, 0xc6, 0xbb, 0x98, 0xa3, 0xc6, 0x57, 0xd0, 0x13, 0x59, 0x72, 0xd4, 0x8d,
	0xde, 0x40, 0xbf, 0xa4, 0xfb, 0x15, 0xba, 0x7d, 0xc0, 0x0c, 0x6a, 0x1e, 0x0f, 0xf6, 0x79, 0x92,
	0x4b, 0x00, 0xb3, 0x19, 0xaf, 0xac, 0xe8, 0xbf, 0x94, 0x21, 0x17, 0xd0, 0x94, 0x8a, 0x09, 0xf5,
	0xcc, 0x14, 0xba, 0x35, 0x5d, 0xde, 0x26, 0x88, 0x0b, 0x27, 0x98, 0x44, 0xba, 0xe6, 0xe8, 0x5a,
	0x1e, 0xd2, 0x6b, 0xe8, 0x2c, 0x50, 0x79, 0x3c, 0xc8, 0x77, 0x61, 0xa3, 0x4d, 0xcd, 0x82, 0xd9,
	0x16, 0xf2, 0x90, 0x7a, 0xd0, 0x2d, 0xb4, 0xf6, 0x36, 0x23, 0x70, 0x96, 0x3c, 0x90, 0x7a, 0x45,
	0x5a, 0xb3, 0xd6, 0xd4, 0x74, 0x34, 0xf5, 0x78, 0xe0, 0xeb, 0xc2, 0xde, 0x7d, 0x19, 0x41, 0xdb,
	0xb0, 0x72, 0xdb, 0x0e, 0x54, 0xe3, 0xc8, 0x3a, 0x56, 0xe3, 0x68, 0xf3, 0x78, 0x46, 0xa0, 0x35,
	0x47, 0x26, 0x42, 0xa1, 0x67, 0x66, 0x78, 0x18, 0x58, 0xd2, 0x1c, 0x06, 0xce, 0xba, 0xd0, 0x36,
	0x73, 0x9b, 0xa3, 0xf8, 0x8a, 0x43, 0x7c, 0x6a, 0xbc, 0xdb, 0x9f, 0x19, 0xd4, 0xf5, 0x47, 0xbd,
	0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x65, 0x77, 0xf0, 0x4b, 0xb9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpiderServiceClient is the client API for SpiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpiderServiceClient interface {
}

type spiderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderServiceClient(cc grpc.ClientConnInterface) SpiderServiceClient {
	return &spiderServiceClient{cc}
}

// SpiderServiceServer is the server API for SpiderService service.
type SpiderServiceServer interface {
}

// UnimplementedSpiderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSpiderServiceServer struct {
}

func RegisterSpiderServiceServer(s *grpc.Server, srv SpiderServiceServer) {
	s.RegisterService(&_SpiderService_serviceDesc, srv)
}

var _SpiderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spider.SpiderService",
	HandlerType: (*SpiderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "scraper.proto",
}
