version: '3.5'

services:
  scraper_service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: scraper-service
    ports:
      - "50051:50051"
    volumes:
      - ../app:/go/src/app/
    environment:
      - ENVIRONMENT=local
      - SCRAPYD_URL=http://159.89.224.233:6800/
    command: go run /go/src/app/main.go
